# Generated by Django 2.2.4 on 2019-09-05 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=4)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer_portal.Buyer')),
            ],
        ),
    ]
