# Generated by Django 2.2.4 on 2019-08-29 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
        migrations.DeleteModel(
            name='Buyer',
        ),
    ]
