# Generated by Django 2.2.4 on 2019-08-31 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='state',
            field=models.CharField(default='WA', max_length=2),
            preserve_default=False,
        ),
    ]
