# Generated by Django 2.2.4 on 2019-09-08 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller_portal', '0002_seller_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cylinders', models.CharField(max_length=1, null=True)),
                ('doors', models.CharField(max_length=1, null=True)),
                ('drive', models.CharField(max_length=60, null=True)),
                ('make', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('series', models.CharField(max_length=20, null=True)),
                ('trim', models.CharField(max_length=20, null=True)),
                ('vin', models.CharField(max_length=17)),
                ('year', models.CharField(max_length=4)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller_portal.Seller')),
            ],
        ),
    ]
